[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
clap = { version = "3.1.6", features = ["derive"] }
async-std = "1.13.0"
async-io = "1.13.0"
futures = "0.3"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread","sync"] }
rand = "0.9.1"
